# Generated by Django 4.2.6 on 2023-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['date_of_birth'], name='profiles_pr_date_of_6d425e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['nationality'], name='profiles_pr_nationa_b9e5ba_idx'),
        ),
    ]
