# Generated by Django 4.2.6 on 2023-10-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_profile_profiles_pr_date_of_6d425e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
