version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    container_name: zplatform_api
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    networks:
      - zplatform-network

  postgres_db:
    image: postgres:12.0-alpine
    container_name: zplatform_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - zplatform-network

  redis:
    image: redis:6-alpine
    container_name: zplatform_redis
    entrypoint: redis-server --appendonly no --save ""
    ports:
      - 6380:6379
    networks:
      - zplatform-network

  worker:
    build:
      context: .
      dockerfile: ./docker/development/django/Dockerfile
    container_name: zplatform_worker
    command: /worker
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - .env
    depends_on:
      - redis
      - api
    networks:
      - zplatform-network

networks:
  zplatform-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
