# Generated by Django 4.2.6 on 2023-10-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firstname'], name='users_user_firstna_e0539d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['lastname'], name='users_user_lastnam_18c5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['middlename'], name='users_user_middlen_5a05d0_idx'),
        ),
    ]
